### ISSUE TITLE
advent of cyber 2 day 24

### ISSUE THREAD

**Issue by aman05382** [flyme2bluemoon/thm-advent#2]
What is the value of the root.txt flag?
only this answer

I have done with all answers but when I trying to get this root.txt I am getting an error there is no value in /path/

please if you have completed then tell me this answer
thank you

**Comment by flyme2bluemoon** [comment]
Have you completed the LXD privilege escalation?

**Comment by aman05382** [comment]
Yes, i have completed
Thank you for replying
